# .github/workflows/main.yml
name: Ruby 2.6.0

on:
  push:
    branches:
      - main

env:
  RUBY_VERSION: 2.6.0
  NRLKEY: ${{ secrets.NRLKEY }} 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: production
    env:
      ImageOS: ubuntu18
      BUILD_NUMBER: ${{ github.run_number }}
      application_name: "testnr"
    steps:
        
      - name: Value NR as secret
        
        run: |
          echo "The NRKEY base 64 secret value"
          echo "MY NR KEY (base64) = $(echo ${NRLKEY} | base64)"


      - name: Checkout testnr Repo.
        uses: actions/checkout@v2


      - name: Install ruby
        uses: ruby/setup-ruby@v1
        env:
          ImageOS: ubuntu18
        with:
          ruby-version: '2.6.0'
    
      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
  
      - name: Bundle Install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          
