# .github/workflows/main.yml
name: Ruby 2.6.0

on:
  push:
    branches:
      - main

env:
  RUBY_VERSION: 2.6.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-node@v2.1.2
      with:
        ruby-version: ${{ env.RUBY_VERSION }}

    - name: Install dependencies
      run: bundle config specific_platform true && bundle install && bundle package

    - name: Run Rake
      run: bundle exec rake && bundle exec rake version:create && bundle config disable_exec_load true

    - name: Zip vendor directory
      run: zip -r vendor.zip vendor/
