# .github/workflows/main.yml
name: Ruby 2.6.0

on:
  push:
    branches:
      - main

env:
  RUBY_VERSION: 2.6.0
  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ImageOS: ubuntu18
      BUILD_NUMBER: ${{ github.run_number }}
      application_name: "testnr"
    steps:
      - name: Set environmental variables 📚
        run: |
          echo "GIT_COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "FEATURE_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed  -E 's/(feature|fix|test|hotfix|bugfix|\/)//g' |  sed  -E 's/ /-/g' |  cut -c1-9 | tr '[:upper:]' '[:lower:]')"  >> $GITHUB_ENV
          echo "SHORT_COMMIT=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
          echo "BUILD_VERSION=${FEATURE_NAME}-${SHORT_COMMIT}" >> $GITHUB_ENV
       - run: 'echo "$NEWRELIC_LICENSE_KEY" | base64'
              shell: bash
              env:
                NEWRELIC_LICENSE_KEY: ${{ secrets.NRLKEY }}


      - name: Checkout testnr Repo.
        uses: actions/checkout@v2


      - name: Install ruby
        uses: ruby/setup-ruby@v1
        env:
          ImageOS: ubuntu18
        with:
          ruby-version: '2.6.0'
    
      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
  
      - name: Bundle Install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          